import numpy as np
from smith_waterman import algs
"""
def test_roc():
    return None

def test_smithwaterman():
    return None
"""

def test_scoring():
	seqA = "SLEAAQKSNVTSSWAKASAAWGTAGPEFFMALFDAHDDVFAKFSGLFSGAAKGTVKNTPEMAAQAQSFKGLVSNWVDNLDNAGALEGQCKTFAANHKARGISAGQLEAAFKVLSGFMKSYGGDEGAWTAVAGALMGEIEPDM"
	#file prot-0004.fa
	seqB = "ANKTRELCMKSLEHAKVDTSNEARQDGIDLYKHMFENYPPLRKYFKSREEYTAEDVQNDPFFAKQGQKILLACHVLCATYDDRETFNAYTRELLDRHARDHVHMPPEVWTDFWKLFEEYLGKKTTLDEPTKQAWHEIGREFAKEINK"
    #file prot-0008.fa

    # update this assertion
	#print(alignedSeq1)
	return algs.sw(seqA, seqB)

